services:
  app:
    build:
      context: python-app/
      dockerfile: Dockerfile
    container_name: yarkostBot
    env_file:
      - python-app/.env
    restart: always
    depends_on:
      pg:
        condition: service_healthy
      minio:
        condition: service_healthy

  pg:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./www:/var/www/certbot
    depends_on:
      minio:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
  minio_data:
