version: '3.3'

services:
  app:
    build:
      context: python-app/
      dockerfile: Dockerfile
    container_name: yarkostBot
    env_file:
      - python-app/.env
    depends_on:
      - pg
      - minio

  pg:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
