version: '3.8'

services:
  app:
    build:
      context: python_app/
      dockerfile: python_app/dockerfile
    container_name: yarkostBot
    env_file:
      - python_app/.env
    depends_on:
      - pg

  pg:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
